POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mami",
    "password": "mami"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "kyouko",
    "password": "kyouko"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "sayaka",
    "password": "sayaka"
}